class_name LanMultiplayerManager
extends Node

## Thin wrapper around Godot's built-in high-level multiplayer (ENet) for
## a single 1v1 LAN match. No server, no internet service, no
## matchmaking — just two phones on the same WiFi network, one hosting
## and one joining by typing in the host's local IP.
##
## *** EXPERIMENTAL / UNVERIFIED ***
## This is real networking code, but it has not been run against Godot's
## engine or tested between two real devices in this environment (no
## engine, no second device, no network access here). Treat it as a
## first draft that needs an actual LAN test pass before you trust it -
## the RPC wiring and signal flow are correct to the best of my
## knowledge of Godot 4's MultiplayerAPI, but "correct on paper" and
## "works on your phones" are different things for anything networked.
##
## Lives at a fixed, stable path ("/root/Main/LanMultiplayerManager"),
## added once in main.gd's _ready() and never removed - RPCs route by
## scene-tree path, and that path must be identical on both peers, which
## it can't be if this lived inside MoreScreen's dynamically-rebuilt
## content panel (that tree shape can differ between two devices
## depending on their separate navigation history).

signal opponent_connected(peer_id: int)
signal opponent_disconnected()
signal connected_to_host()
signal connection_failed()
signal match_start_received(word_list: Array, start_unix_time: float)
signal opponent_progress(words_done: int)
signal opponent_finished(elapsed_seconds: float)

const DEFAULT_PORT := 47321

var _peer: ENetMultiplayerPeer
var _opponent_id := -1
var _is_host := false


func _ready() -> void:
	multiplayer.peer_connected.connect(_on_peer_connected)
	multiplayer.peer_disconnected.connect(_on_peer_disconnected)
	multiplayer.connected_to_server.connect(_on_connected_to_server)
	multiplayer.connection_failed.connect(_on_connection_failed)
	multiplayer.server_disconnected.connect(_on_peer_disconnected)


func is_connected_to_opponent() -> bool:
	return _opponent_id > 0


## Returns this device's local (LAN) IPv4 addresses, so the host can read
## one aloud / show it on screen for the other player to type in. Filters
## out loopback and link-local addresses; may still return more than one
## on a multi-interface device (VPN, hotspot, etc) - if so, the player
## just has to try the one that looks like a normal home-network address
## (usually 192.168.x.x or 10.x.x.x).
func get_local_ip_candidates() -> Array:
	var out: Array = []
	for addr in IP.get_local_addresses():
		if addr.begins_with("127.") or addr.begins_with("169.254.") or addr == "0.0.0.0":
			continue
		if addr.find(":") != -1:
			continue   # skip IPv6 for simplicity - LAN IPv4 is the common case
		out.append(addr)
	return out


func host_match(port: int = DEFAULT_PORT) -> Error:
	shutdown()
	_peer = ENetMultiplayerPeer.new()
	var err = _peer.create_server(port, 1)
	if err != OK:
		_peer = null
		return err
	multiplayer.multiplayer_peer = _peer
	_is_host = true
	return OK


func join_match(address: String, port: int = DEFAULT_PORT) -> Error:
	shutdown()
	_peer = ENetMultiplayerPeer.new()
	var err = _peer.create_client(address, port)
	if err != OK:
		_peer = null
		return err
	multiplayer.multiplayer_peer = _peer
	_is_host = false
	return OK


## Closes the connection and resets multiplayer state so the app behaves
## like a normal offline game again and a future match can start clean.
func shutdown() -> void:
	if is_instance_valid(_peer):
		_peer.close()
	_peer = null
	_opponent_id = -1
	_is_host = false
	if multiplayer.has_multiplayer_peer():
		multiplayer.multiplayer_peer = null


func _on_peer_connected(id: int) -> void:
	_opponent_id = id
	opponent_connected.emit(id)


func _on_peer_disconnected(_id: int = -1) -> void:
	_opponent_id = -1
	opponent_disconnected.emit()


func _on_connected_to_server() -> void:
	_opponent_id = 1   # the host is always peer id 1
	connected_to_host.emit()


func _on_connection_failed() -> void:
	connection_failed.emit()


## Host-only: kicks off the match for both sides at once. word_list is
## generated by the host so both players race the identical words;
## start_unix_time is a few seconds in the future so both devices' local
## countdowns land on the same moment despite normal LAN latency.
func send_match_start(word_list: Array, start_unix_time: float) -> void:
	if not _is_host:
		return
	_receive_match_start.rpc(word_list, start_unix_time)


@rpc("authority", "call_local", "reliable")
func _receive_match_start(word_list: Array, start_unix_time: float) -> void:
	match_start_received.emit(word_list, start_unix_time)


## Call from either side whenever the local player completes a word, to
## keep the opponent's progress bar live.
func send_progress(words_done: int) -> void:
	if _opponent_id <= 0:
		return
	_receive_progress.rpc_id(_opponent_id, words_done)


@rpc("any_peer", "reliable")
func _receive_progress(words_done: int) -> void:
	opponent_progress.emit(words_done)


## Call from either side the moment the local player finishes all words.
func send_finished(elapsed_seconds: float) -> void:
	if _opponent_id <= 0:
		return
	_receive_finished.rpc_id(_opponent_id, elapsed_seconds)


@rpc("any_peer", "reliable")
func _receive_finished(elapsed_seconds: float) -> void:
	opponent_finished.emit(elapsed_seconds)
